### ISSUE TITLE
Getting HttpError: Not Found

### ISSUE THREAD

**Issue by Hemant11111** [barecheck/code-coverage-action#230]
```
            - name: Backend Code Coverage report
              id: code-coverage
              uses: barecheck/code-coverage-action@v1
              with:
                barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
                lcov-file: "apps/func/coverage/lcov.info"
                send-summary-comment: true
                show-annotations: "warning"
              env:
                BARECHECK_GITHUB_APP_TOKEN: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
 ```              
  
  Output: 
lcov-file: apps/func/coverage/lcov.info
Current code coverage: 48.29%
Base branch code coverage: 0%
Code coverage diff: 48.29%
Code coverage diff: 48.29%
HttpError: Not Found
Error: Not Found
