### ISSUE TITLE
Uncovered files and lines are not appearing in the comments.

### ISSUE THREAD

**Issue by halitdogmen** [barecheck/code-coverage-action#290]
First of all, I'm not sure if the configurations are correct. I was running a simple test to integrate it into the pipelines, but I didn't get the expected result. I wanted to share this with you.

Job configuration is as follows.

```yaml
- name: Generate Code Coverage Report
  id: code-coverage
  uses: barecheck/code-coverage-action@v1
  with:
    barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
    lcov-file: "source_coverage.lcov.info"
    base-lcov-file: "target_coverage.lcov.info"
    send-summary-comment: true
    show-annotations: "warning"
```

The output in the comments is as follows.
![image](https://github.com/user-attachments/assets/726a7252-6ef2-4590-af16-a31efe25f742)

Could you please help resolve this so that uncovered files and lines appear as expected in the comments?

Lcov Files:
[lcov-files.zip](https://github.com/user-attachments/files/17531879/lcov-files.zip)
