### ISSUE TITLE
Code coverage comment is not working for Forks based PR

### ISSUE THREAD

**Issue by vitaliimelnychuk** [barecheck/code-coverage-action#59]
```
UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /home/runner/work/code-coverage-action/code-coverage-action/dist/index.js:3441:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createComment (/home/runner/work/code-coverage-action/code-coverage-action/dist/index.js:6221:15)
    at async sendSummaryComment (/home/runner/work/code-coverage-action/code-coverage-action/dist/index.js:6050:5)
    at async runFeatures (/home/runner/work/code-coverage-action/code-coverage-action/dist/index.js:6671:3)
    at async runCodeCoverage (/home/runner/work/code-coverage-action/code-coverage-action/dist/index.js:6692:3)
    at async main (/home/runner/work/code-coverage-action/code-coverage-action/dist/index.js:6709:3)
(node:2193) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2193) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
For reference, https://github.com/barecheck/code-coverage-action/pull/55. There is an action that is marked as successfully finished but, there is an error inside, mentioned above. 

As result, there is no GitHub code coverage report from the action.

**Comment by melnychukvitaliy** [comment]
https://github.com/actions/first-interaction/issues/10

**Comment by keyseven123** [comment]
Hi @vitaliimelnychuk ,
I am not sure, if I should create a new bug report as the title somehow fits to a bug, I am currently experiencing. 
I am getting the following output from your action. 
![image](https://github.com/user-attachments/assets/9b75d21d-59f2-42eb-a570-c7bb9f56de5b)

I am using the following github parameters:
``` yaml
      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: pr-coverage.lcov
          base-lcov-file: ref-coverage.lcov
          send-summary-comment: true
          show-annotations: "warning"
```


I have also attached the lcov 
files for the base and the pr branch. 
If you need anything else, please do not hesitate to ask.
[ref-coverage.lcov.txt](https://github.com/user-attachments/files/16678059/ref-coverage.lcov.txt)
[pr-coverage.lcov.txt](https://github.com/user-attachments/files/16678058/pr-coverage.lcov.txt)
